In [6]:
import pyspark
import numpy as np
import pandas as pd

In [5]:
## Generating wordcount dataset
unique_words = ['Cat','Dog','Bird','Plane','Tiger','Man','Woman','Car','Boat','Bear','Fox','Worm']
k = 10000
dataset_path = '../data/wordcount_dataset.txt'

words = np.random.choice(unique_words, k)
data = ' '.join(words)
with open(dataset_path, 'w', encoding='utf-8') as fd:
    fd.write(data)

In [7]:
dataset_path = '../data/small_openfoodfacts.csv'
df = pd.read_csv(dataset_path, sep='\t')

In [10]:
df.describe()

,code,created_t,last_modified_t,last_updated_t,abbreviated_product_name,cities,allergens_en,serving_quantity,additives_n,additives,...,glycemic-index_100g,water-hardness_100g,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g
count,1.000000e+03,1.000000e+03,1.000000e+03,9.990000e+02,0.0,0.0,0.0,256.000000,344.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,1.010976e+16,1.555023e+09,1.582110e+09,1.707695e+09,NaN,NaN,NaN,56.598828,0.918605,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.163008e+17,6.815055e+07,6.713032e+07,6.936859e+05,NaN,NaN,NaN,65.401161,1.712347,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000e+00,1.345024e+09,1.444659e+09,1.707490e+09,NaN,NaN,NaN,0.000000,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,4.525000e+03,1.489138e+09,1.539581e+09,1.707490e+09,NaN,NaN,NaN,28.300000,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,5.826600e+04,1.538836e+09,1.550285e+09,1.707603e+09,NaN,NaN,NaN,40.000000,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2.753303e+07,1.594806e+09,1.644568e+09,1.707739e+09,NaN,NaN,NaN,56.000000,1.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000214e+19,1.714495e+09,1.714665e+09,1.714665e+09,NaN,NaN,NaN,600.000000,10.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN